version: "3"
services:
 frontend:
  build: ./dndroller-frontend/
  ports:
   - "80:80"
 dndroller:
  image: dndroller:1.0-SNAPSHOT
  environment:
   - APPLICATION_SECRET="UPVWf7KXATsV3l>su55z:PLqk8p0yXzYGkw>L<FAkOmH<_^pS/jg/XALfR70J<a/"
  ports:
   - "9000:9000"
 mongo:
  image: mongo:latest
